config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # devise_for :users
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :favorites
  resources :products do 
    collection do
      get 'search', to: 'products#search'
    end
  end
  resources :order_items do 
    collection do
      post 'create', to: 'order_items#create'
      # patch 'update', to: 'order_items#update'
    end
  end
  resources :shops #, only:[:index, :show]
  # root 'products#index'
  # get 'shops#index'
  get 'cart', to: 'cart#show'
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    if params[:filter]
      @products = Product.where(category:params[:filter])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @favorite_exists = Favorite.where(product_id: @product.id, user_id: current_user.id) == [] ? false : true
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<% @products.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |product| %>
      <div class='col-md-3'>
        <strong class="card-text"><%= product.name %></strong>
        <div><%= sanitize(product.description) %></div>
        <div><%= product.category %></div>
        <div><%= number_to_currency(product.price) %></div> 
        <div><%= link_to 'Show', shop_path(product) %></div>
        <%# <%= button_to 'Add to Cart', add_to_cart_path(product_id: product.id), class: 'btn btn-info btn-sm', remote: true %>
        <%= form_with model: @order_items, url: order_items_path do |f| %>
            <div class="field">
                <%= f.hidden_field :product_id, value: product.id %>
                <%= f.hidden_field :quantity, value: 1, min: 1 %>
            </div>
            <div class="actions">
                <div>
                    <%= f.submit "Add to Cart", class: 'btn btn-success' %>
                </div>
            </div>
        <% end %>
        <div>
          <%= button_to favorite_text, favorite_path(product.id), id: 'favorite_link', method: :put, remote: true, class: 'btn btn-primary' %>
        </div>
        <hr>
      </div>
    <% end %>
  </div>
<% end %>

<br>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= form_with model: @order_items, url: order_items_path do |f| %>
  <div class="field">
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.number_field :quantity, value: 1, min: 1 %>
  </div>
    <div class="actions">
  <%= f.submit "Add to Cart", class: 'btn btn-success' %>
  </div>
<% end %>

<%# <%= link_to 'Back', root_path %>
<%= link_to 'Back', shops_path %>