config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # devise_for :users
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :favorites
  resources :products do 
    collection do
      get 'search', to: 'products#search'
    end
  end
  resources :order_items do 
    collection do
      post 'create', to: 'order_items#create'
      # patch 'update', to: 'order_items#update'
    end
  end
  resources :shops #, only:[:index, :show]
  # root 'products#index'
  # get 'shops#index'
  get 'cart', to: 'cart#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :products
    
    # def add_item(product_id)
    #     product = Product.where('id = ?', product_id).first
    #     cart = []
    #     if product
    #         cart << product
    #     end
    # end

    # def total_price
    #     products.to_a.sum(&:full_price)
    # end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
        order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product
    belongs_to :order
    before_save :set_unit_price
    before_save :set_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end
  
    def total
        return unit_price * quantity
    end

    private

    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total * quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items

    has_many :favorites
    has_many :users, through: :favorites

    scope :search_by_name, ->(query) { where(["lower(name) LIKE ?", "%#{query.downcase}%"]) }
    scope :search_by_description, ->(query) { where(["lower(description) LIKE ?", "%#{query.downcase}%"]) }

    def self.search(query)
        search_by_name(query) || search_by_description(query) 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :products, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_forgery_protection

    include ApplicationHelper
    # before_action :authenticate_user! , except: [:home]

    # def current_cart
    #     if session[:cart_id]
    #       @current_cart ||= Cart.find(session[:cart_id])
    #     end
    #     if session[:cart_id].nil?
    #       @current_cart = Cart.create!
    #       session[:cart_id] = @current_cart.id
    #     end
    #     @current_cart
    # end

    def favorite_text
        return @favorite_exists ? "Remove from Favorites" : "Add to Favorites"
    end

    helper_method :favorite_text
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    # @cart = current_cart
    @order_items = current_cart.order_items
  end

  # def add_to_cart
  #     current_cart.add_item(params[:product_id])
  #     redirect_to carts_path(current_cart.id)
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
  end

  def index
  end

  def update
    product = Product.find(params[:id])
    favorites = Favorite.where(product_id: product.id, user_id: current_user.id)

    if favorites == []
      Favorite.create!(product_id: product.id, user_id: current_user.id)
      @favorite_exists = true
    else
      favorites.destroy_all
      @favorite_exists = false
    end

    redirect_to shops_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @products = Product.all
    # @order_item = current_cart.order_items.create # new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # GET /products/search
  def search
    @products = Product.search(params[:product])
    render 'shops/index'
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :category, :description, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    if params[:filter]
      @products = Product.where(category:params[:filter])
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @favorite_exists = Favorite.where(product_id: @product.id, user_id: current_user.id) == [] ? false : true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_cart
        if Order.find_by_id(session[:order_id]).nil?
            Order.create! # new
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galaxy Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <div class="container-fluid">
          <a class="navbar-brand" href=""> <%= link_to "Galaxy Store", root_path %> </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <%# <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li> %>
              <%# <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> %>
              <%# <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search product" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> %>
              <%= form_tag search_products_path, method: :get do %>
                <%# <div class="form-group row"> %>
                  <%= text_field_tag :product, params[:product], placeholder: 'Search product' %>
                  <%= button_tag type: :submit, class: "btn btn-outline-success" do %>
                    <%= 'Search' %> 
                  <% end %>
                <%# </div> %>
              <% end %>
              <li class="nav-item dropdown" style="padding-left: 50px;">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Products
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li class="dropdown-item"> <%= link_to 'Phones', shops_path(:filter => "Phone") %></li>
                  <li class="dropdown-item"> <%= link_to 'PCs', shops_path(:filter => "PC") %></li>
                  <li class="dropdown-item"> <%= link_to 'Laptops', shops_path(:filter => "Laptop") %></li>
                </ul>
              </li>
              <%# <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> %>
            </ul>
            <%# <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search product" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'My Cart', cart_path %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item" style="padding-left: 20px;">
                  <%# <a class="nav-link active" aria-current="page" href="#">Favorites</a> %>
                  <%= link_to 'Favorites', favorites_path %>
                </li>
              <% end %>
              <li class="nav-item dropdown" style="padding-left: 20px;">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%# <li><a class="dropdown-item" href="#">Login</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Sign Up</a></li> %>
                <% if user_signed_in? %>
                  <li class="dropdown-item"><%= link_to "Hi, #{current_user.email}", edit_user_registration_path %></li>
                  <li class="dropdown-item">My orders</li>
                  <li class="dropdown-item">Return products</li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="dropdown-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li class="dropdown-item"><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="dropdown-item"><%= link_to 'Sign Up', new_user_registration_path %></li>
                <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>